name: Python ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests (dataset validation)
      - name: Run dataset tests
        run: python test.py

      # 5. Run ML training pipeline
      - name: Run ML training
        run: python train_model.py

      # 6. Upload all output artifacts
      - name: Upload output artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-results
          path: |
            ConfusionMatrix.png
            FeatureImportance.png
            scores.txt
            test.txt
